services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: mychat-app
    ports:
      - "5173:5173"
    volumes:
      - .:/home/appuser/app
      - node_modules:/home/appuser/app/node_modules
    mem_limit: 8g
    environment:
      - NODE_ENV=development
    working_dir: /home/appuser/app
    command: yarn dev -- --host 0.0.0.0

volumes:
  node_modules:
