version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/home/appuser/app
      - node_modules:/home/appuser/app/node_modules
      - yarn-cache:/usr/local/share/.cache/yarn
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["sh", "-c", "yarn install && yarn dev --host"]
    network_mode: "host"
  yarn:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/home/appuser/app
      - node_modules:/home/appuser/app/node_modules
      - yarn-cache:/usr/local/share/.cache/yarn
    command: ["sh", "-c", "yarn install"]

volumes:
  node_modules:
  yarn-cache:
