services:
  app:
    platform: ${PLATFORM:-linux/arm64}
    build:
      context: .
      args:
        - USER_ID=${UID:-501}
        - GROUP_ID=${GID:-20}
    container_name: mychat-app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - ./.pnpm-store:/home/node/.local/share/pnpm/store
      - ./.pnpm-cache:/home/node/.cache/pnpm
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PNPM_HOME=/home/node/.local/share/pnpm
    working_dir: /app
    command: sh -c "pnpm dev:host"
