services:
  app:
    build: .
    container_name: ${CONTAINER_NAME:-mychat-app}
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - pnpm-store:/root/.local/share/pnpm/store
      - pnpm-cache:/root/.cache/pnpm
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: sh -c "pnpm install && pnpm dev:host"

volumes:
  pnpm-store:
  pnpm-cache:
