FROM node:22-slim

# Install dependencies for Puppeteer
RUN apt-get update && apt-get install -y \
    chromium \
    libatk-bridge2.0-0 \
    libgtk-3-0 \
    libasound2 \
    fonts-freefont-ttf \
    libxss1 \
    libxtst6 \
    xauth \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables for Puppeteer
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

# Create working directory
WORKDIR /visual-tests

# Install dependencies
RUN npm init -y && \
    npm install puppeteer pixelmatch canvas

# Set entrypoint to bash
ENTRYPOINT ["/bin/bash"]