services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ${CONTAINER_NAME:-mychat-app}
    ports:
      - "5173:5173"
    volumes:
      - .:/home/appuser/app
      - /home/appuser/app/node_modules # This excludes node_modules from host mounting
    environment:
      - NODE_ENV=development
    working_dir: /home/appuser/app
    command: pnpm dev:host
