services:
  app:
    platform: ${PLATFORM:-linux/arm64}
    build:
      context: .
      args:
        - USER_ID=${UID:-501}
        - GROUP_ID=${GID:-501}
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-mychat}-app
    ports:
      - "5173:5173"
      - "3000:3000"  # Add this if you need the API port
    volumes:
      - type: bind
        source: .
        target: /app
        bind:
          create_host_path: true
      # PNPM store for package data
      - type: volume
        source: pnpm_store
        target: /home/node/.local/share/pnpm/store
        volume:
          nocopy: false  # Allow initial copy
      # PNPM cache for metadata
      - type: volume
        source: pnpm_cache
        target: /home/node/.cache/pnpm
        volume:
          nocopy: false  # Allow initial copy
      # Node modules
      - type: volume
        source: node_modules
        target: /app/node_modules
        volume:
          nocopy: false  # Allow initial copy
    environment:
      - NODE_ENV=development
      - PNPM_HOME=/home/node/.local/share/pnpm
      - PATH=/home/node/.local/share/pnpm:$PATH
      - PACKAGE_HASH=${PACKAGE_HASH:-default}
      - PNPM_STORE_DIR=/home/node/.local/share/pnpm/store
      - PNPM_CACHE_DIR=/home/node/.cache/pnpm
      - UID=${UID}
      - GID=${GID}
      - VITE_SIM_MODE=${VITE_SIM_MODE:-false}
      - VITE_DEV_SERVER_FORCE_CLOSE=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app
    network_mode: "host"
    command: sh -c "pnpm dev:host"
    stop_signal: SIGINT
    stop_grace_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

volumes:
  node_modules:
    name: "mychat-node_modules"
    external: true
  pnpm_store:
    name: "mychat-pnpm_store"
    external: true
  pnpm_cache:
    name: "mychat-pnpm_cache"
    external: true
