services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app:cached  # Source code for hot reloading
      - /app/node_modules  # Keep modules in container
    environment:
      - NODE_ENV=development
    command: yarn dev
    network_mode: "host"

  yarn-tools:
    build:
      context: .
      target: development
    volumes:
      - .:/app:cached
      - /app/node_modules
    profiles: ["tools"]
    environment:
      - NODE_ENV=test
    # Usage:
    # docker compose --profile tools run yarn-tools yarn deps:update
    # docker compose --profile tools run yarn-tools yarn deps:force
    # docker compose --profile tools run yarn-tools yarn test
