services:
  app:
    platform: ${PLATFORM:-linux/arm64}
    build:
      context: .
      args:
        - USER_ID=${UID:-501}
        - GROUP_ID=${GID:-501}
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-mychat}-app
    ports:
      - "5173:5173"
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /app
        bind:
          create_host_path: true
      - type: volume
        source: node_modules
        target: /app/node_modules
      - type: volume
        source: pnpm_store
        target: /home/node/.local/share/pnpm/store
        volume:
          nocopy: false
      - type: volume
        source: pnpm_cache
        target: /home/node/.cache/pnpm
        volume:
          nocopy: false
      - type: volume
        source: vite_cache
        target: /app/node_modules/.vite
        volume:
          nocopy: false
    environment:
      - NODE_ENV
      - PNPM_HOME=/home/node/.local/share/pnpm
      - PATH=/home/node/.local/share/pnpm:$PATH
      - PACKAGE_HASH=${PACKAGE_HASH:-default}
      - PNPM_STORE_DIR=/home/node/.local/share/pnpm/store
      - PNPM_CACHE_DIR=/home/node/.cache/pnpm
      - UID=${UID}
      - GID=${GID}
      - VITE_DEV_SERVER_FORCE_CLOSE=true
    stop_signal: SIGINT
    stop_grace_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 4G

  shell:
    extends: app
    profiles: ["shell"]
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  node_modules:
    name: "mychat-node_modules"
    external: true
  pnpm_store:
    name: "mychat-pnpm_store"
    external: true
  pnpm_cache:
    name: "mychat-pnpm_cache"
    external: true
  vite_cache:
    name: "mychat-vite_cache"
    external: true
