version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "5173:5173"
#    volumes:
#      - .:/home/appuser/app
#      - /home/appuser/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
#    command: ["sh"]
    command: ["sh", "-c", "yarn dev --host"]
