name: CI/CD Pipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - accept-references

permissions:
  contents: write
  pages: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  lint-typecheck:
    runs-on: ubuntu-latest
    container:
      image: node:22-slim
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1
      - run: pnpm install
      - name: Lint code
        run: pnpm lint:all
      - name: Type check
        run: pnpm type:check:all

  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: node:22-slim
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1
      - run: pnpm install
      - run: pnpm test
      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  build-test:
    runs-on: ubuntu-latest
    container:
      image: node:22-slim
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1
      - run: PNPM_FROZEN_LOCKFILE=true pnpm install
      - run: NODE_ENV=production pnpm build:vite
      - name: Validate source maps
        run: node scripts/analyze-maps.js --validate
      - name: Install CA certificates
        run: |
          apt-get update && apt-get install -y ca-certificates
          update-ca-certificates

      - name: Upload source maps to Sentry
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: pixelcrate
          SENTRY_PROJECT: chatai
          SENTRY_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
        run: pnpm sentry:upload
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/

  visual-tests:
    runs-on: ubuntu-latest
    # Add environment configuration for Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.event.inputs.action != 'accept-references'
    services:
      selenium:
        image: selenium/standalone-chromium:latest
        options: --shm-size="2g"
        ports:
          - 4444:4444
          - 7900:7900
      app:
        image: node:22-slim
        ports:
          - 5173:5173
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1
      
      # Install dependencies
      - name: Install dependencies
        run: pnpm install
      
      # Configure Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Start app in background
      - name: Build and start app for testing
        run: |
          NODE_ENV=production pnpm build:vite
          cd dist && npx serve -s -l 5173 &
          echo "Waiting for app to start..."
          sleep 15

      # Run BackstopJS tests
      - name: Run visual tests
        id: backstop_test
        continue-on-error: true
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium"
        run: |
          pnpm backstop test || true
          echo "status=$?" >> $GITHUB_OUTPUT

      # Download existing pages content if available
      - name: Download existing pages content
        id: download_pages
        continue-on-error: true
        run: |
          # Try to download the existing pages content
          mkdir -p existing-pages
          curl -L https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/index.html -o existing-pages/index.html || true
          if [ -f existing-pages/index.html ]; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      # Prepare report with branch-specific path
      - name: Prepare report for GitHub Pages
        if: always()
        run: |
          # Get branch name or use PR number
          if [[ $GITHUB_REF == refs/pull/* ]]; then
            BRANCH_PATH="pr-$(echo $GITHUB_REF | sed 's/refs\/pull\///' | sed 's/\/merge//')"
          else
            BRANCH_PATH=$(echo $GITHUB_REF | sed 's/refs\/heads\///' | sed 's/\//-/g')
          fi
          
          echo "Publishing to branch path: $BRANCH_PATH"
          
          # Create a directory for the complete report
          mkdir -p gh-pages-report/$BRANCH_PATH
          
          # Copy the HTML report
          cp -r backstop_data/html_report/* gh-pages-report/$BRANCH_PATH/
          
          # Create directories for images
          mkdir -p gh-pages-report/$BRANCH_PATH/bitmaps_reference
          mkdir -p gh-pages-report/$BRANCH_PATH/bitmaps_test
          
          # Copy reference images
          cp -r backstop_data/bitmaps_reference/* gh-pages-report/$BRANCH_PATH/bitmaps_reference/ || true
          
          # Copy test images and diffs
          cp -r backstop_data/bitmaps_test/* gh-pages-report/$BRANCH_PATH/bitmaps_test/ || true
          
          # Fix paths in config.js
          sed -i "s/\.\.\/bitmaps_reference/\.\/bitmaps_reference/g" gh-pages-report/$BRANCH_PATH/config.js
          sed -i "s/\.\.\/bitmaps_test/\.\/bitmaps_test/g" gh-pages-report/$BRANCH_PATH/config.js
          
          # Create an index page that links to all reports
          echo "<html><head><title>Visual Test Reports</title><style>body{font-family:sans-serif;max-width:800px;margin:0 auto;padding:20px}</style></head><body>" > gh-pages-report/index.html
          echo "<h1>Visual Test Reports</h1><ul>" >> gh-pages-report/index.html
          echo "<li><a href='./$BRANCH_PATH/'>$BRANCH_PATH (Latest - $(date))</a></li>" >> gh-pages-report/index.html
          echo "</ul></body></html>" >> gh-pages-report/index.html

      # Upload Pages artifact with complete report
      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'gh-pages-report'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4

      # Update PR comment with branch-specific URL
      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            // Get PR number for the path
            const prNumber = context.issue.number;
            const branchPath = `pr-${prNumber}`;
            
            const reportUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/${branchPath}`;
            const acceptUrl = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/workflows/ci.yml`;
            
            const comment = `
            ## Visual Regression Test Results
            
            📊 [View Full Report](${reportUrl})
            📑 [View All Reports](https://${context.repo.owner}.github.io/${context.repo.repo}/)
      
            If the changes are intentional, you can accept them as new references:
            1. Go to [CI Workflow](${acceptUrl})
            2. Click "Run workflow"
            3. Select "accept-references" from the dropdown
            4. Click "Run workflow"
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      # Upload test results as artifacts
      - name: Upload visual test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backstop-report
          path: backstop_data/

  accept-references:
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'accept-references'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1

      - name: Install dependencies
        run: pnpm install

      - name: Accept References
        run: |
          pnpm backstop approve
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git add backstop_data/bitmaps_reference
          git commit -m "Update visual references [skip ci]"
          git push origin main

  deploy-preview:
    needs: [lint-typecheck, unit-tests, build-test, visual-tests]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist
      # Add your deployment steps here
      - name: Deploy to preview environment
        run: echo "Deploying to preview environment"
        # This would typically use a service like Vercel, Netlify, etc.

  # Add this job to implement E2E tests on the preview deployment
  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1
      - run: PNPM_FROZEN_LOCKFILE=true pnpm install
      
      # Set up environment variables for API keys
      - name: Set up environment variables
        env:
          TEST_OPENAI_API_KEY: ${{ secrets.TEST_OPENAI_API_KEY }}
          TEST_ANTHROPIC_API_KEY: ${{ secrets.TEST_ANTHROPIC_API_KEY }}
        run: |
          echo "TEST_OPENAI_API_KEY=${TEST_OPENAI_API_KEY}" >> $GITHUB_ENV
          echo "TEST_ANTHROPIC_API_KEY=${TEST_ANTHROPIC_API_KEY}" >> $GITHUB_ENV
      
      # Build the app for testing
      - name: Build app
        run: NODE_ENV=production pnpm build:vite
      
      # Start the app in the background
      - name: Start app for testing
        run: |
          cd dist && npx serve -s -l 5173 &
          echo "Waiting for app to start..."
          sleep 5
      
      # Run Playwright tests
      - name: Run E2E tests
        run: pnpm test:e2e
      
      # Upload test results and artifacts
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
      # Upload test traces for debugging
      - name: Upload test traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/
          retention-days: 7

  # Add this job to implement Production Build and Deploy
  deploy-production:
    needs: [lint-typecheck, unit-tests, build-test, visual-tests]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1
      - run: PNPM_FROZEN_LOCKFILE=true pnpm install
      - run: NODE_ENV=production pnpm build:vite
      - name: Deploy to production
        run: echo "Deploying to production"
        # This would typically use a service like Vercel, Netlify, etc.
